CREATE TABLE UsuariosEslabon
(
	Id INT IDENTITY PRIMARY KEY,
	Usuario VARCHAR(50) NOT NULL,
	Correo VARCHAR(50) NOT NULL,
	Contrasena VARBINARY(MAX) NOT NULL,
	Llave VARBINARY(MAX) NOT NULL,
	Estatus BIT NOT NULL,
	Sexo VARCHAR(9) NOT NULL,
	FechaCreacion DATE NOT NULL
);